// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/proto/fluke.proto

package flukeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{0}
}

type StepOutcome int32

const (
	StepOutcome_STEP_OUTCOME_UNSPECIFIED StepOutcome = 0
	StepOutcome_STEP_OUTCOME_SKIPPED     StepOutcome = 1 // Check passed — command not run
	StepOutcome_STEP_OUTCOME_SUCCESS     StepOutcome = 2 // Command ran and exited 0
	StepOutcome_STEP_OUTCOME_FAILED      StepOutcome = 3 // Command ran and exited non-zero
)

// Enum value maps for StepOutcome.
var (
	StepOutcome_name = map[int32]string{
		0: "STEP_OUTCOME_UNSPECIFIED",
		1: "STEP_OUTCOME_SKIPPED",
		2: "STEP_OUTCOME_SUCCESS",
		3: "STEP_OUTCOME_FAILED",
	}
	StepOutcome_value = map[string]int32{
		"STEP_OUTCOME_UNSPECIFIED": 0,
		"STEP_OUTCOME_SKIPPED":     1,
		"STEP_OUTCOME_SUCCESS":     2,
		"STEP_OUTCOME_FAILED":      3,
	}
)

func (x StepOutcome) Enum() *StepOutcome {
	p := new(StepOutcome)
	*p = x
	return p
}

func (x StepOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[1].Descriptor()
}

func (StepOutcome) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[1]
}

func (x StepOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepOutcome.Descriptor instead.
func (StepOutcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{1}
}

type CheckOutcome int32

const (
	CheckOutcome_CHECK_OUTCOME_UNSPECIFIED     CheckOutcome = 0
	CheckOutcome_CHECK_OUTCOME_SATISFIED       CheckOutcome = 1
	CheckOutcome_CHECK_OUTCOME_DRIFT           CheckOutcome = 2
	CheckOutcome_CHECK_OUTCOME_EXECUTION_ERROR CheckOutcome = 3
)

// Enum value maps for CheckOutcome.
var (
	CheckOutcome_name = map[int32]string{
		0: "CHECK_OUTCOME_UNSPECIFIED",
		1: "CHECK_OUTCOME_SATISFIED",
		2: "CHECK_OUTCOME_DRIFT",
		3: "CHECK_OUTCOME_EXECUTION_ERROR",
	}
	CheckOutcome_value = map[string]int32{
		"CHECK_OUTCOME_UNSPECIFIED":     0,
		"CHECK_OUTCOME_SATISFIED":       1,
		"CHECK_OUTCOME_DRIFT":           2,
		"CHECK_OUTCOME_EXECUTION_ERROR": 3,
	}
)

func (x CheckOutcome) Enum() *CheckOutcome {
	p := new(CheckOutcome)
	*p = x
	return p
}

func (x CheckOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[2].Descriptor()
}

func (CheckOutcome) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[2]
}

func (x CheckOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckOutcome.Descriptor instead.
func (CheckOutcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{2}
}

type TaskOutcome int32

const (
	TaskOutcome_TASK_OUTCOME_UNSPECIFIED TaskOutcome = 0
	TaskOutcome_TASK_OUTCOME_SUCCESS     TaskOutcome = 1 // All steps succeeded or were satisfied
	TaskOutcome_TASK_OUTCOME_FAILED      TaskOutcome = 2 // Aborted due to step failure
	TaskOutcome_TASK_OUTCOME_CANCELLED   TaskOutcome = 3 // Cancelled via CancelTask
)

// Enum value maps for TaskOutcome.
var (
	TaskOutcome_name = map[int32]string{
		0: "TASK_OUTCOME_UNSPECIFIED",
		1: "TASK_OUTCOME_SUCCESS",
		2: "TASK_OUTCOME_FAILED",
		3: "TASK_OUTCOME_CANCELLED",
	}
	TaskOutcome_value = map[string]int32{
		"TASK_OUTCOME_UNSPECIFIED": 0,
		"TASK_OUTCOME_SUCCESS":     1,
		"TASK_OUTCOME_FAILED":      2,
		"TASK_OUTCOME_CANCELLED":   3,
	}
)

func (x TaskOutcome) Enum() *TaskOutcome {
	p := new(TaskOutcome)
	*p = x
	return p
}

func (x TaskOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[3].Descriptor()
}

func (TaskOutcome) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[3]
}

func (x TaskOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskOutcome.Descriptor instead.
func (TaskOutcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{3}
}

type OnFailure int32

const (
	OnFailure_ON_FAILURE_ABORT    OnFailure = 0 // Default — stop task on step failure
	OnFailure_ON_FAILURE_CONTINUE OnFailure = 1 // Proceed to next step despite failure
)

// Enum value maps for OnFailure.
var (
	OnFailure_name = map[int32]string{
		0: "ON_FAILURE_ABORT",
		1: "ON_FAILURE_CONTINUE",
	}
	OnFailure_value = map[string]int32{
		"ON_FAILURE_ABORT":    0,
		"ON_FAILURE_CONTINUE": 1,
	}
)

func (x OnFailure) Enum() *OnFailure {
	p := new(OnFailure)
	*p = x
	return p
}

func (x OnFailure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnFailure) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[4].Descriptor()
}

func (OnFailure) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[4]
}

func (x OnFailure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnFailure.Descriptor instead.
func (OnFailure) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{4}
}

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNKNOWN      AgentStatus = 0
	AgentStatus_AGENT_STATUS_CONNECTED    AgentStatus = 1
	AgentStatus_AGENT_STATUS_DISCONNECTED AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_CONNECTED",
		2: "AGENT_STATUS_DISCONNECTED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":      0,
		"AGENT_STATUS_CONNECTED":    1,
		"AGENT_STATUS_DISCONNECTED": 2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fluke_proto_enumTypes[5].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_fluke_proto_enumTypes[5]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{5}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_StateReport
	//	*AgentMessage_LogLine
	//	*AgentMessage_StepResult
	//	*AgentMessage_TaskComplete
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_proto_fluke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetStateReport() *StateReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StateReport); ok {
			return x.StateReport
		}
	}
	return nil
}

func (x *AgentMessage) GetLogLine() *StepLogLine {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_LogLine); ok {
			return x.LogLine
		}
	}
	return nil
}

func (x *AgentMessage) GetStepResult() *StepResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StepResult); ok {
			return x.StepResult
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskComplete() *TaskComplete {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskComplete); ok {
			return x.TaskComplete
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_StateReport struct {
	StateReport *StateReport `protobuf:"bytes,2,opt,name=state_report,json=stateReport,proto3,oneof"`
}

type AgentMessage_LogLine struct {
	LogLine *StepLogLine `protobuf:"bytes,3,opt,name=log_line,json=logLine,proto3,oneof"`
}

type AgentMessage_StepResult struct {
	StepResult *StepResult `protobuf:"bytes,4,opt,name=step_result,json=stepResult,proto3,oneof"`
}

type AgentMessage_TaskComplete struct {
	TaskComplete *TaskComplete `protobuf:"bytes,5,opt,name=task_complete,json=taskComplete,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_StateReport) isAgentMessage_Payload() {}

func (*AgentMessage_LogLine) isAgentMessage_Payload() {}

func (*AgentMessage_StepResult) isAgentMessage_Payload() {}

func (*AgentMessage_TaskComplete) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_RequestStateReport
	//	*ServerMessage_ExecuteTask
	//	*ServerMessage_CancelTask
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_proto_fluke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetRequestStateReport() *RequestStateReport {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RequestStateReport); ok {
			return x.RequestStateReport
		}
	}
	return nil
}

func (x *ServerMessage) GetExecuteTask() *ExecuteTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ExecuteTask); ok {
			return x.ExecuteTask
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelTask() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_RequestStateReport struct {
	RequestStateReport *RequestStateReport `protobuf:"bytes,2,opt,name=request_state_report,json=requestStateReport,proto3,oneof"`
}

type ServerMessage_ExecuteTask struct {
	ExecuteTask *ExecuteTask `protobuf:"bytes,3,opt,name=execute_task,json=executeTask,proto3,oneof"`
}

type ServerMessage_CancelTask struct {
	CancelTask *CancelTask `protobuf:"bytes,4,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_RequestStateReport) isServerMessage_Payload() {}

func (*ServerMessage_ExecuteTask) isServerMessage_Payload() {}

func (*ServerMessage_CancelTask) isServerMessage_Payload() {}

// RegisterRequest is the first message sent by an agent when it connects.
// hostname is resolved automatically via os.Hostname() — not user-configured.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// RegisterAck acknowledges successful registration and provides the
// server-assigned agent_id for this connection session.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_internal_proto_fluke_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type RequestStateReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"` // Correlation ID echoed back in StateReport
	Tasks         []*TaskSpec            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStateReport) Reset() {
	*x = RequestStateReport{}
	mi := &file_internal_proto_fluke_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStateReport) ProtoMessage() {}

func (x *RequestStateReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStateReport.ProtoReflect.Descriptor instead.
func (*RequestStateReport) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{4}
}

func (x *RequestStateReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RequestStateReport) GetTasks() []*TaskSpec {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type StateReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"` // Echoes RequestStateReport.report_id
	TaskStates    []*TaskState           `protobuf:"bytes,2,rep,name=task_states,json=taskStates,proto3" json:"task_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateReport) Reset() {
	*x = StateReport{}
	mi := &file_internal_proto_fluke_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReport) ProtoMessage() {}

func (x *StateReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReport.ProtoReflect.Descriptor instead.
func (*StateReport) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{5}
}

func (x *StateReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *StateReport) GetTaskStates() []*TaskState {
	if x != nil {
		return x.TaskStates
	}
	return nil
}

type TaskState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	StepResults   []*StepCheckResult     `protobuf:"bytes,2,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_internal_proto_fluke_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{6}
}

func (x *TaskState) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskState) GetStepResults() []*StepCheckResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

// StepCheckResult is the outcome of running a step's check expression.
// satisfied=true means the check exited 0 — the step is already done.
// satisfied=false (or no check present) means the step needs to run.
type StepCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Satisfied     bool                   `protobuf:"varint,2,opt,name=satisfied,proto3" json:"satisfied,omitempty"`                                                      // Deprecated compatibility field.
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`                                                             // Check stderr, useful for debugging.
	CheckOutcome  CheckOutcome           `protobuf:"varint,4,opt,name=check_outcome,json=checkOutcome,proto3,enum=fluke.v1.CheckOutcome" json:"check_outcome,omitempty"` // Explicit check operation outcome.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepCheckResult) Reset() {
	*x = StepCheckResult{}
	mi := &file_internal_proto_fluke_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCheckResult) ProtoMessage() {}

func (x *StepCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCheckResult.ProtoReflect.Descriptor instead.
func (*StepCheckResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{7}
}

func (x *StepCheckResult) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepCheckResult) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *StepCheckResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StepCheckResult) GetCheckOutcome() CheckOutcome {
	if x != nil {
		return x.CheckOutcome
	}
	return CheckOutcome_CHECK_OUTCOME_UNSPECIFIED
}

type ExecuteTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"` // Correlation ID for this execution run
	Task          *TaskSpec              `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_internal_proto_fluke_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteTask) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteTask) GetTask() *TaskSpec {
	if x != nil {
		return x.Task
	}
	return nil
}

// CancelTask instructs the agent to abort a running task.
type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_internal_proto_fluke_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTask) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// StepLogLine carries incremental stdout/stderr output from a running step.
// These are emitted as output is produced, before StepResult is sent.
type StepLogLine struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId     string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepName        string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Stream          LogStream              `protobuf:"varint,3,opt,name=stream,proto3,enum=fluke.v1.LogStream" json:"stream,omitempty"`
	Text            string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // One line or chunk of output
	TimestampUnixMs int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepLogLine) Reset() {
	*x = StepLogLine{}
	mi := &file_internal_proto_fluke_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepLogLine) ProtoMessage() {}

func (x *StepLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepLogLine.ProtoReflect.Descriptor instead.
func (*StepLogLine) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{10}
}

func (x *StepLogLine) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StepLogLine) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepLogLine) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *StepLogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StepLogLine) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// StepResult reports the final outcome of a step. stdout/stderr are not
// repeated here — they were already streamed via StepLogLine.
type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Outcome       StepOutcome            `protobuf:"varint,3,opt,name=outcome,proto3,enum=fluke.v1.StepOutcome" json:"outcome,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_internal_proto_fluke_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{11}
}

func (x *StepResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StepResult) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepResult) GetOutcome() StepOutcome {
	if x != nil {
		return x.Outcome
	}
	return StepOutcome_STEP_OUTCOME_UNSPECIFIED
}

func (x *StepResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StepResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// TaskComplete signals that a task execution has ended, successfully or not.
type TaskComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Outcome       TaskOutcome            `protobuf:"varint,2,opt,name=outcome,proto3,enum=fluke.v1.TaskOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskComplete) Reset() {
	*x = TaskComplete{}
	mi := &file_internal_proto_fluke_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskComplete) ProtoMessage() {}

func (x *TaskComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskComplete.ProtoReflect.Descriptor instead.
func (*TaskComplete) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{12}
}

func (x *TaskComplete) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TaskComplete) GetOutcome() TaskOutcome {
	if x != nil {
		return x.Outcome
	}
	return TaskOutcome_TASK_OUTCOME_UNSPECIFIED
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_proto_fluke_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{13}
}

func (x *Heartbeat) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// TaskSpec is the server's compiled representation of a task, sent to agents.
// All HCL variables and locals are resolved before transmission — agents
// never see or parse HCL directly.
type TaskSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Steps                []*StepSpec            `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,4,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"` // 0 = use server default (180)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_internal_proto_fluke_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{14}
}

func (x *TaskSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskSpec) GetSteps() []*StepSpec {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *TaskSpec) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

// StepSpec is a single step within a TaskSpec.
type StepSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Check         string                 `protobuf:"bytes,3,opt,name=check,proto3" json:"check,omitempty"` // Optional idempotency check expression
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RunAs         string                 `protobuf:"bytes,6,opt,name=run_as,json=runAs,proto3" json:"run_as,omitempty"` // Optional — unix user to run as via sudo
	OnFailure     OnFailure              `protobuf:"varint,7,opt,name=on_failure,json=onFailure,proto3,enum=fluke.v1.OnFailure" json:"on_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepSpec) Reset() {
	*x = StepSpec{}
	mi := &file_internal_proto_fluke_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepSpec) ProtoMessage() {}

func (x *StepSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepSpec.ProtoReflect.Descriptor instead.
func (*StepSpec) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{15}
}

func (x *StepSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StepSpec) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *StepSpec) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StepSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StepSpec) GetRunAs() string {
	if x != nil {
		return x.RunAs
	}
	return ""
}

func (x *StepSpec) GetOnFailure() OnFailure {
	if x != nil {
		return x.OnFailure
	}
	return OnFailure_ON_FAILURE_ABORT
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{16}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSummary        `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_internal_proto_fluke_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{17}
}

func (x *ListAgentsResponse) GetAgents() []*AgentSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"` // Stable across reconnects; use AgentSummary.hostname from ListAgents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{18}
}

func (x *GetAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentSummary          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Events        []*EventSummary        `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"` // Recent reconciliation history for this agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_internal_proto_fluke_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{19}
}

func (x *GetAgentResponse) GetAgent() *AgentSummary {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *GetAgentResponse) GetEvents() []*EventSummary {
	if x != nil {
		return x.Events
	}
	return nil
}

type AgentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        AgentStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=fluke.v1.AgentStatus" json:"status,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,5,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSummary) Reset() {
	*x = AgentSummary{}
	mi := &file_internal_proto_fluke_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSummary) ProtoMessage() {}

func (x *AgentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSummary.ProtoReflect.Descriptor instead.
func (*AgentSummary) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{20}
}

func (x *AgentSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSummary) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentSummary) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentSummary) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

func (x *AgentSummary) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

type ListDriftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriftRequest) Reset() {
	*x = ListDriftRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriftRequest) ProtoMessage() {}

func (x *ListDriftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriftRequest.ProtoReflect.Descriptor instead.
func (*ListDriftRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{21}
}

type ListDriftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DriftEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriftResponse) Reset() {
	*x = ListDriftResponse{}
	mi := &file_internal_proto_fluke_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriftResponse) ProtoMessage() {}

func (x *ListDriftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriftResponse.ProtoReflect.Descriptor instead.
func (*ListDriftResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{22}
}

func (x *ListDriftResponse) GetEntries() []*DriftEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DriftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	StepName      string                 `protobuf:"bytes,4,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	DetectedUnix  int64                  `protobuf:"varint,5,opt,name=detected_unix,json=detectedUnix,proto3" json:"detected_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftEntry) Reset() {
	*x = DriftEntry{}
	mi := &file_internal_proto_fluke_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftEntry) ProtoMessage() {}

func (x *DriftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftEntry.ProtoReflect.Descriptor instead.
func (*DriftEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{23}
}

func (x *DriftEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DriftEntry) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DriftEntry) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *DriftEntry) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *DriftEntry) GetDetectedUnix() int64 {
	if x != nil {
		return x.DetectedUnix
	}
	return 0
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`    // Optional filter
	TaskName      string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"` // Optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 0 = use server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{24}
}

func (x *ListEventsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListEventsRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventSummary        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_internal_proto_fluke_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{25}
}

func (x *ListEventsResponse) GetEvents() []*EventSummary {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TaskName      string                 `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Outcome       TaskOutcome            `protobuf:"varint,5,opt,name=outcome,proto3,enum=fluke.v1.TaskOutcome" json:"outcome,omitempty"`
	StartedUnix   int64                  `protobuf:"varint,6,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	EndedUnix     int64                  `protobuf:"varint,7,opt,name=ended_unix,json=endedUnix,proto3" json:"ended_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSummary) Reset() {
	*x = EventSummary{}
	mi := &file_internal_proto_fluke_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSummary) ProtoMessage() {}

func (x *EventSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSummary.ProtoReflect.Descriptor instead.
func (*EventSummary) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{26}
}

func (x *EventSummary) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventSummary) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EventSummary) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *EventSummary) GetOutcome() TaskOutcome {
	if x != nil {
		return x.Outcome
	}
	return TaskOutcome_TASK_OUTCOME_UNSPECIFIED
}

func (x *EventSummary) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *EventSummary) GetEndedUnix() int64 {
	if x != nil {
		return x.EndedUnix
	}
	return 0
}

type StreamExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExecutionRequest) Reset() {
	*x = StreamExecutionRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExecutionRequest) ProtoMessage() {}

func (x *StreamExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExecutionRequest.ProtoReflect.Descriptor instead.
func (*StreamExecutionRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{27}
}

func (x *StreamExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// ExecutionEvent is a forwarded event from the AgentService stream,
// fanned out to management clients watching a specific execution.
type ExecutionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecutionEvent_LogLine
	//	*ExecutionEvent_StepResult
	//	*ExecutionEvent_TaskComplete
	Event         isExecutionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_internal_proto_fluke_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{28}
}

func (x *ExecutionEvent) GetEvent() isExecutionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecutionEvent) GetLogLine() *StepLogLine {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_LogLine); ok {
			return x.LogLine
		}
	}
	return nil
}

func (x *ExecutionEvent) GetStepResult() *StepResult {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_StepResult); ok {
			return x.StepResult
		}
	}
	return nil
}

func (x *ExecutionEvent) GetTaskComplete() *TaskComplete {
	if x != nil {
		if x, ok := x.Event.(*ExecutionEvent_TaskComplete); ok {
			return x.TaskComplete
		}
	}
	return nil
}

type isExecutionEvent_Event interface {
	isExecutionEvent_Event()
}

type ExecutionEvent_LogLine struct {
	LogLine *StepLogLine `protobuf:"bytes,1,opt,name=log_line,json=logLine,proto3,oneof"`
}

type ExecutionEvent_StepResult struct {
	StepResult *StepResult `protobuf:"bytes,2,opt,name=step_result,json=stepResult,proto3,oneof"`
}

type ExecutionEvent_TaskComplete struct {
	TaskComplete *TaskComplete `protobuf:"bytes,3,opt,name=task_complete,json=taskComplete,proto3,oneof"`
}

func (*ExecutionEvent_LogLine) isExecutionEvent_Event() {}

func (*ExecutionEvent_StepResult) isExecutionEvent_Event() {}

func (*ExecutionEvent_TaskComplete) isExecutionEvent_Event() {}

type TriggerReconcileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*TriggerReconcileRequest_TaskName
	//	*TriggerReconcileRequest_AgentId
	//	*TriggerReconcileRequest_All
	Target        isTriggerReconcileRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerReconcileRequest) Reset() {
	*x = TriggerReconcileRequest{}
	mi := &file_internal_proto_fluke_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerReconcileRequest) ProtoMessage() {}

func (x *TriggerReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerReconcileRequest.ProtoReflect.Descriptor instead.
func (*TriggerReconcileRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{29}
}

func (x *TriggerReconcileRequest) GetTarget() isTriggerReconcileRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TriggerReconcileRequest) GetTaskName() string {
	if x != nil {
		if x, ok := x.Target.(*TriggerReconcileRequest_TaskName); ok {
			return x.TaskName
		}
	}
	return ""
}

func (x *TriggerReconcileRequest) GetAgentId() string {
	if x != nil {
		if x, ok := x.Target.(*TriggerReconcileRequest_AgentId); ok {
			return x.AgentId
		}
	}
	return ""
}

func (x *TriggerReconcileRequest) GetAll() bool {
	if x != nil {
		if x, ok := x.Target.(*TriggerReconcileRequest_All); ok {
			return x.All
		}
	}
	return false
}

type isTriggerReconcileRequest_Target interface {
	isTriggerReconcileRequest_Target()
}

type TriggerReconcileRequest_TaskName struct {
	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3,oneof"` // All agents whose labels match this task's selector
}

type TriggerReconcileRequest_AgentId struct {
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof"` // All tasks matching this agent's labels
}

type TriggerReconcileRequest_All struct {
	All bool `protobuf:"varint,3,opt,name=all,proto3,oneof"` // Everything
}

func (*TriggerReconcileRequest_TaskName) isTriggerReconcileRequest_Target() {}

func (*TriggerReconcileRequest_AgentId) isTriggerReconcileRequest_Target() {}

func (*TriggerReconcileRequest_All) isTriggerReconcileRequest_Target() {}

type ReconciliationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ReconciliationEvent_Started
	//	*ReconciliationEvent_AgentStarted
	//	*ReconciliationEvent_Execution
	//	*ReconciliationEvent_AgentResult
	//	*ReconciliationEvent_Complete
	Event         isReconciliationEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconciliationEvent) Reset() {
	*x = ReconciliationEvent{}
	mi := &file_internal_proto_fluke_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationEvent) ProtoMessage() {}

func (x *ReconciliationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationEvent.ProtoReflect.Descriptor instead.
func (*ReconciliationEvent) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{30}
}

func (x *ReconciliationEvent) GetEvent() isReconciliationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ReconciliationEvent) GetStarted() *ReconcileStarted {
	if x != nil {
		if x, ok := x.Event.(*ReconciliationEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ReconciliationEvent) GetAgentStarted() *AgentReconcileStarted {
	if x != nil {
		if x, ok := x.Event.(*ReconciliationEvent_AgentStarted); ok {
			return x.AgentStarted
		}
	}
	return nil
}

func (x *ReconciliationEvent) GetExecution() *ExecutionEvent {
	if x != nil {
		if x, ok := x.Event.(*ReconciliationEvent_Execution); ok {
			return x.Execution
		}
	}
	return nil
}

func (x *ReconciliationEvent) GetAgentResult() *AgentReconcileResult {
	if x != nil {
		if x, ok := x.Event.(*ReconciliationEvent_AgentResult); ok {
			return x.AgentResult
		}
	}
	return nil
}

func (x *ReconciliationEvent) GetComplete() *ReconcileComplete {
	if x != nil {
		if x, ok := x.Event.(*ReconciliationEvent_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isReconciliationEvent_Event interface {
	isReconciliationEvent_Event()
}

type ReconciliationEvent_Started struct {
	Started *ReconcileStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"` // Emitted once at the beginning
}

type ReconciliationEvent_AgentStarted struct {
	AgentStarted *AgentReconcileStarted `protobuf:"bytes,2,opt,name=agent_started,json=agentStarted,proto3,oneof"` // Per agent as it begins
}

type ReconciliationEvent_Execution struct {
	Execution *ExecutionEvent `protobuf:"bytes,3,opt,name=execution,proto3,oneof"` // Forwarded live from AgentService
}

type ReconciliationEvent_AgentResult struct {
	AgentResult *AgentReconcileResult `protobuf:"bytes,4,opt,name=agent_result,json=agentResult,proto3,oneof"` // Per agent when it finishes
}

type ReconciliationEvent_Complete struct {
	Complete *ReconcileComplete `protobuf:"bytes,5,opt,name=complete,proto3,oneof"` // Final event — stream closes after
}

func (*ReconciliationEvent_Started) isReconciliationEvent_Event() {}

func (*ReconciliationEvent_AgentStarted) isReconciliationEvent_Event() {}

func (*ReconciliationEvent_Execution) isReconciliationEvent_Event() {}

func (*ReconciliationEvent_AgentResult) isReconciliationEvent_Event() {}

func (*ReconciliationEvent_Complete) isReconciliationEvent_Event() {}

type ReconcileStarted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentsTargeted int32                  `protobuf:"varint,1,opt,name=agents_targeted,json=agentsTargeted,proto3" json:"agents_targeted,omitempty"`
	StartedUnix    int64                  `protobuf:"varint,2,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconcileStarted) Reset() {
	*x = ReconcileStarted{}
	mi := &file_internal_proto_fluke_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileStarted) ProtoMessage() {}

func (x *ReconcileStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileStarted.ProtoReflect.Descriptor instead.
func (*ReconcileStarted) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{31}
}

func (x *ReconcileStarted) GetAgentsTargeted() int32 {
	if x != nil {
		return x.AgentsTargeted
	}
	return 0
}

func (x *ReconcileStarted) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

type AgentReconcileStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReconcileStarted) Reset() {
	*x = AgentReconcileStarted{}
	mi := &file_internal_proto_fluke_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReconcileStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReconcileStarted) ProtoMessage() {}

func (x *AgentReconcileStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReconcileStarted.ProtoReflect.Descriptor instead.
func (*AgentReconcileStarted) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{32}
}

func (x *AgentReconcileStarted) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReconcileStarted) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentReconcileStarted) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

type AgentReconcileResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TaskName      string                 `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Outcome       TaskOutcome            `protobuf:"varint,4,opt,name=outcome,proto3,enum=fluke.v1.TaskOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReconcileResult) Reset() {
	*x = AgentReconcileResult{}
	mi := &file_internal_proto_fluke_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReconcileResult) ProtoMessage() {}

func (x *AgentReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReconcileResult.ProtoReflect.Descriptor instead.
func (*AgentReconcileResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{33}
}

func (x *AgentReconcileResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentReconcileResult) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentReconcileResult) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *AgentReconcileResult) GetOutcome() TaskOutcome {
	if x != nil {
		return x.Outcome
	}
	return TaskOutcome_TASK_OUTCOME_UNSPECIFIED
}

type ReconcileComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     int32                  `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	Skipped       int32                  `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"` // Agents already in desired state — no execution dispatched
	EndedUnix     int64                  `protobuf:"varint,4,opt,name=ended_unix,json=endedUnix,proto3" json:"ended_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileComplete) Reset() {
	*x = ReconcileComplete{}
	mi := &file_internal_proto_fluke_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileComplete) ProtoMessage() {}

func (x *ReconcileComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fluke_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileComplete.ProtoReflect.Descriptor instead.
func (*ReconcileComplete) Descriptor() ([]byte, []int) {
	return file_internal_proto_fluke_proto_rawDescGZIP(), []int{34}
}

func (x *ReconcileComplete) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *ReconcileComplete) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ReconcileComplete) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ReconcileComplete) GetEndedUnix() int64 {
	if x != nil {
		return x.EndedUnix
	}
	return 0
}

var File_internal_proto_fluke_proto protoreflect.FileDescriptor

const file_internal_proto_fluke_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/fluke.proto\x12\bfluke.v1\"\xef\x02\n" +
	"\fAgentMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.fluke.v1.RegisterRequestH\x00R\bregister\x12:\n" +
	"\fstate_report\x18\x02 \x01(\v2\x15.fluke.v1.StateReportH\x00R\vstateReport\x122\n" +
	"\blog_line\x18\x03 \x01(\v2\x15.fluke.v1.StepLogLineH\x00R\alogLine\x127\n" +
	"\vstep_result\x18\x04 \x01(\v2\x14.fluke.v1.StepResultH\x00R\n" +
	"stepResult\x12=\n" +
	"\rtask_complete\x18\x05 \x01(\v2\x16.fluke.v1.TaskCompleteH\x00R\ftaskComplete\x123\n" +
	"\theartbeat\x18\x06 \x01(\v2\x13.fluke.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x9d\x02\n" +
	"\rServerMessage\x12:\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x15.fluke.v1.RegisterAckH\x00R\vregisterAck\x12P\n" +
	"\x14request_state_report\x18\x02 \x01(\v2\x1c.fluke.v1.RequestStateReportH\x00R\x12requestStateReport\x12:\n" +
	"\fexecute_task\x18\x03 \x01(\v2\x15.fluke.v1.ExecuteTaskH\x00R\vexecuteTask\x127\n" +
	"\vcancel_task\x18\x04 \x01(\v2\x14.fluke.v1.CancelTaskH\x00R\n" +
	"cancelTaskB\t\n" +
	"\apayload\"\xa7\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.fluke.v1.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\vRegisterAck\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"[\n" +
	"\x12RequestStateReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12(\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.fluke.v1.TaskSpecR\x05tasks\"`\n" +
	"\vStateReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x124\n" +
	"\vtask_states\x18\x02 \x03(\v2\x13.fluke.v1.TaskStateR\n" +
	"taskStates\"f\n" +
	"\tTaskState\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12<\n" +
	"\fstep_results\x18\x02 \x03(\v2\x19.fluke.v1.StepCheckResultR\vstepResults\"\xa1\x01\n" +
	"\x0fStepCheckResult\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1c\n" +
	"\tsatisfied\x18\x02 \x01(\bR\tsatisfied\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12;\n" +
	"\rcheck_outcome\x18\x04 \x01(\x0e2\x16.fluke.v1.CheckOutcomeR\fcheckOutcome\"X\n" +
	"\vExecuteTask\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.fluke.v1.TaskSpecR\x04task\"/\n" +
	"\n" +
	"CancelTask\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xba\x01\n" +
	"\vStepLogLine\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12+\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x13.fluke.v1.LogStreamR\x06stream\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\"\xbb\x01\n" +
	"\n" +
	"StepResult\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12/\n" +
	"\aoutcome\x18\x03 \x01(\x0e2\x15.fluke.v1.StepOutcomeR\aoutcome\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"b\n" +
	"\fTaskComplete\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12/\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x15.fluke.v1.TaskOutcomeR\aoutcome\"2\n" +
	"\tHeartbeat\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\"\xa0\x01\n" +
	"\bTaskSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x05steps\x18\x03 \x03(\v2\x12.fluke.v1.StepSpecR\x05steps\x124\n" +
	"\x16check_interval_seconds\x18\x04 \x01(\x05R\x14checkIntervalSeconds\"\xa1\x02\n" +
	"\bStepSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x14\n" +
	"\x05check\x18\x03 \x01(\tR\x05check\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12-\n" +
	"\x03env\x18\x05 \x03(\v2\x1b.fluke.v1.StepSpec.EnvEntryR\x03env\x12\x15\n" +
	"\x06run_as\x18\x06 \x01(\tR\x05runAs\x122\n" +
	"\n" +
	"on_failure\x18\a \x01(\x0e2\x13.fluke.v1.OnFailureR\tonFailure\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ListAgentsRequest\"D\n" +
	"\x12ListAgentsResponse\x12.\n" +
	"\x06agents\x18\x01 \x03(\v2\x16.fluke.v1.AgentSummaryR\x06agents\"-\n" +
	"\x0fGetAgentRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"p\n" +
	"\x10GetAgentResponse\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.fluke.v1.AgentSummaryR\x05agent\x12.\n" +
	"\x06events\x18\x02 \x03(\v2\x16.fluke.v1.EventSummaryR\x06events\"\x91\x02\n" +
	"\fAgentSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".fluke.v1.AgentSummary.LabelsEntryR\x06labels\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.fluke.v1.AgentStatusR\x06status\x12$\n" +
	"\x0elast_seen_unix\x18\x05 \x01(\x03R\flastSeenUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10ListDriftRequest\"C\n" +
	"\x11ListDriftResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.fluke.v1.DriftEntryR\aentries\"\xa2\x01\n" +
	"\n" +
	"DriftEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12\x1b\n" +
	"\tstep_name\x18\x04 \x01(\tR\bstepName\x12#\n" +
	"\rdetected_unix\x18\x05 \x01(\x03R\fdetectedUnix\"a\n" +
	"\x11ListEventsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"D\n" +
	"\x12ListEventsResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.fluke.v1.EventSummaryR\x06events\"\xf0\x01\n" +
	"\fEventSummary\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1b\n" +
	"\ttask_name\x18\x04 \x01(\tR\btaskName\x12/\n" +
	"\aoutcome\x18\x05 \x01(\x0e2\x15.fluke.v1.TaskOutcomeR\aoutcome\x12!\n" +
	"\fstarted_unix\x18\x06 \x01(\x03R\vstartedUnix\x12\x1d\n" +
	"\n" +
	"ended_unix\x18\a \x01(\x03R\tendedUnix\";\n" +
	"\x16StreamExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xc5\x01\n" +
	"\x0eExecutionEvent\x122\n" +
	"\blog_line\x18\x01 \x01(\v2\x15.fluke.v1.StepLogLineH\x00R\alogLine\x127\n" +
	"\vstep_result\x18\x02 \x01(\v2\x14.fluke.v1.StepResultH\x00R\n" +
	"stepResult\x12=\n" +
	"\rtask_complete\x18\x03 \x01(\v2\x16.fluke.v1.TaskCompleteH\x00R\ftaskCompleteB\a\n" +
	"\x05event\"s\n" +
	"\x17TriggerReconcileRequest\x12\x1d\n" +
	"\ttask_name\x18\x01 \x01(\tH\x00R\btaskName\x12\x1b\n" +
	"\bagent_id\x18\x02 \x01(\tH\x00R\aagentId\x12\x12\n" +
	"\x03all\x18\x03 \x01(\bH\x00R\x03allB\b\n" +
	"\x06target\"\xd8\x02\n" +
	"\x13ReconciliationEvent\x126\n" +
	"\astarted\x18\x01 \x01(\v2\x1a.fluke.v1.ReconcileStartedH\x00R\astarted\x12F\n" +
	"\ragent_started\x18\x02 \x01(\v2\x1f.fluke.v1.AgentReconcileStartedH\x00R\fagentStarted\x128\n" +
	"\texecution\x18\x03 \x01(\v2\x18.fluke.v1.ExecutionEventH\x00R\texecution\x12C\n" +
	"\fagent_result\x18\x04 \x01(\v2\x1e.fluke.v1.AgentReconcileResultH\x00R\vagentResult\x129\n" +
	"\bcomplete\x18\x05 \x01(\v2\x1b.fluke.v1.ReconcileCompleteH\x00R\bcompleteB\a\n" +
	"\x05event\"^\n" +
	"\x10ReconcileStarted\x12'\n" +
	"\x0fagents_targeted\x18\x01 \x01(\x05R\x0eagentsTargeted\x12!\n" +
	"\fstarted_unix\x18\x02 \x01(\x03R\vstartedUnix\"k\n" +
	"\x15AgentReconcileStarted\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\"\x9b\x01\n" +
	"\x14AgentReconcileResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12/\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x15.fluke.v1.TaskOutcomeR\aoutcome\"\x82\x01\n" +
	"\x11ReconcileComplete\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12\x18\n" +
	"\askipped\x18\x03 \x01(\x05R\askipped\x12\x1d\n" +
	"\n" +
	"ended_unix\x18\x04 \x01(\x03R\tendedUnix*U\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02*x\n" +
	"\vStepOutcome\x12\x1c\n" +
	"\x18STEP_OUTCOME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STEP_OUTCOME_SKIPPED\x10\x01\x12\x18\n" +
	"\x14STEP_OUTCOME_SUCCESS\x10\x02\x12\x17\n" +
	"\x13STEP_OUTCOME_FAILED\x10\x03*\x86\x01\n" +
	"\fCheckOutcome\x12\x1d\n" +
	"\x19CHECK_OUTCOME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CHECK_OUTCOME_SATISFIED\x10\x01\x12\x17\n" +
	"\x13CHECK_OUTCOME_DRIFT\x10\x02\x12!\n" +
	"\x1dCHECK_OUTCOME_EXECUTION_ERROR\x10\x03*z\n" +
	"\vTaskOutcome\x12\x1c\n" +
	"\x18TASK_OUTCOME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_OUTCOME_SUCCESS\x10\x01\x12\x17\n" +
	"\x13TASK_OUTCOME_FAILED\x10\x02\x12\x1a\n" +
	"\x16TASK_OUTCOME_CANCELLED\x10\x03*:\n" +
	"\tOnFailure\x12\x14\n" +
	"\x10ON_FAILURE_ABORT\x10\x00\x12\x17\n" +
	"\x13ON_FAILURE_CONTINUE\x10\x01*b\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16AGENT_STATUS_CONNECTED\x10\x01\x12\x1d\n" +
	"\x19AGENT_STATUS_DISCONNECTED\x10\x022N\n" +
	"\fAgentService\x12>\n" +
	"\aConnect\x12\x16.fluke.v1.AgentMessage\x1a\x17.fluke.v1.ServerMessage(\x010\x012\xd7\x03\n" +
	"\x11ManagementService\x12G\n" +
	"\n" +
	"ListAgents\x12\x1b.fluke.v1.ListAgentsRequest\x1a\x1c.fluke.v1.ListAgentsResponse\x12A\n" +
	"\bGetAgent\x12\x19.fluke.v1.GetAgentRequest\x1a\x1a.fluke.v1.GetAgentResponse\x12D\n" +
	"\tListDrift\x12\x1a.fluke.v1.ListDriftRequest\x1a\x1b.fluke.v1.ListDriftResponse\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.fluke.v1.ListEventsRequest\x1a\x1c.fluke.v1.ListEventsResponse\x12O\n" +
	"\x0fStreamExecution\x12 .fluke.v1.StreamExecutionRequest\x1a\x18.fluke.v1.ExecutionEvent0\x01\x12V\n" +
	"\x10TriggerReconcile\x12!.fluke.v1.TriggerReconcileRequest\x1a\x1d.fluke.v1.ReconciliationEvent0\x01B5Z3github.com/taiidani/fluke/internal/proto/flukeprotob\x06proto3"

var (
	file_internal_proto_fluke_proto_rawDescOnce sync.Once
	file_internal_proto_fluke_proto_rawDescData []byte
)

func file_internal_proto_fluke_proto_rawDescGZIP() []byte {
	file_internal_proto_fluke_proto_rawDescOnce.Do(func() {
		file_internal_proto_fluke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_fluke_proto_rawDesc), len(file_internal_proto_fluke_proto_rawDesc)))
	})
	return file_internal_proto_fluke_proto_rawDescData
}

var file_internal_proto_fluke_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_internal_proto_fluke_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_internal_proto_fluke_proto_goTypes = []any{
	(LogStream)(0),                  // 0: fluke.v1.LogStream
	(StepOutcome)(0),                // 1: fluke.v1.StepOutcome
	(CheckOutcome)(0),               // 2: fluke.v1.CheckOutcome
	(TaskOutcome)(0),                // 3: fluke.v1.TaskOutcome
	(OnFailure)(0),                  // 4: fluke.v1.OnFailure
	(AgentStatus)(0),                // 5: fluke.v1.AgentStatus
	(*AgentMessage)(nil),            // 6: fluke.v1.AgentMessage
	(*ServerMessage)(nil),           // 7: fluke.v1.ServerMessage
	(*RegisterRequest)(nil),         // 8: fluke.v1.RegisterRequest
	(*RegisterAck)(nil),             // 9: fluke.v1.RegisterAck
	(*RequestStateReport)(nil),      // 10: fluke.v1.RequestStateReport
	(*StateReport)(nil),             // 11: fluke.v1.StateReport
	(*TaskState)(nil),               // 12: fluke.v1.TaskState
	(*StepCheckResult)(nil),         // 13: fluke.v1.StepCheckResult
	(*ExecuteTask)(nil),             // 14: fluke.v1.ExecuteTask
	(*CancelTask)(nil),              // 15: fluke.v1.CancelTask
	(*StepLogLine)(nil),             // 16: fluke.v1.StepLogLine
	(*StepResult)(nil),              // 17: fluke.v1.StepResult
	(*TaskComplete)(nil),            // 18: fluke.v1.TaskComplete
	(*Heartbeat)(nil),               // 19: fluke.v1.Heartbeat
	(*TaskSpec)(nil),                // 20: fluke.v1.TaskSpec
	(*StepSpec)(nil),                // 21: fluke.v1.StepSpec
	(*ListAgentsRequest)(nil),       // 22: fluke.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 23: fluke.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),         // 24: fluke.v1.GetAgentRequest
	(*GetAgentResponse)(nil),        // 25: fluke.v1.GetAgentResponse
	(*AgentSummary)(nil),            // 26: fluke.v1.AgentSummary
	(*ListDriftRequest)(nil),        // 27: fluke.v1.ListDriftRequest
	(*ListDriftResponse)(nil),       // 28: fluke.v1.ListDriftResponse
	(*DriftEntry)(nil),              // 29: fluke.v1.DriftEntry
	(*ListEventsRequest)(nil),       // 30: fluke.v1.ListEventsRequest
	(*ListEventsResponse)(nil),      // 31: fluke.v1.ListEventsResponse
	(*EventSummary)(nil),            // 32: fluke.v1.EventSummary
	(*StreamExecutionRequest)(nil),  // 33: fluke.v1.StreamExecutionRequest
	(*ExecutionEvent)(nil),          // 34: fluke.v1.ExecutionEvent
	(*TriggerReconcileRequest)(nil), // 35: fluke.v1.TriggerReconcileRequest
	(*ReconciliationEvent)(nil),     // 36: fluke.v1.ReconciliationEvent
	(*ReconcileStarted)(nil),        // 37: fluke.v1.ReconcileStarted
	(*AgentReconcileStarted)(nil),   // 38: fluke.v1.AgentReconcileStarted
	(*AgentReconcileResult)(nil),    // 39: fluke.v1.AgentReconcileResult
	(*ReconcileComplete)(nil),       // 40: fluke.v1.ReconcileComplete
	nil,                             // 41: fluke.v1.RegisterRequest.LabelsEntry
	nil,                             // 42: fluke.v1.StepSpec.EnvEntry
	nil,                             // 43: fluke.v1.AgentSummary.LabelsEntry
}
var file_internal_proto_fluke_proto_depIdxs = []int32{
	8,  // 0: fluke.v1.AgentMessage.register:type_name -> fluke.v1.RegisterRequest
	11, // 1: fluke.v1.AgentMessage.state_report:type_name -> fluke.v1.StateReport
	16, // 2: fluke.v1.AgentMessage.log_line:type_name -> fluke.v1.StepLogLine
	17, // 3: fluke.v1.AgentMessage.step_result:type_name -> fluke.v1.StepResult
	18, // 4: fluke.v1.AgentMessage.task_complete:type_name -> fluke.v1.TaskComplete
	19, // 5: fluke.v1.AgentMessage.heartbeat:type_name -> fluke.v1.Heartbeat
	9,  // 6: fluke.v1.ServerMessage.register_ack:type_name -> fluke.v1.RegisterAck
	10, // 7: fluke.v1.ServerMessage.request_state_report:type_name -> fluke.v1.RequestStateReport
	14, // 8: fluke.v1.ServerMessage.execute_task:type_name -> fluke.v1.ExecuteTask
	15, // 9: fluke.v1.ServerMessage.cancel_task:type_name -> fluke.v1.CancelTask
	41, // 10: fluke.v1.RegisterRequest.labels:type_name -> fluke.v1.RegisterRequest.LabelsEntry
	20, // 11: fluke.v1.RequestStateReport.tasks:type_name -> fluke.v1.TaskSpec
	12, // 12: fluke.v1.StateReport.task_states:type_name -> fluke.v1.TaskState
	13, // 13: fluke.v1.TaskState.step_results:type_name -> fluke.v1.StepCheckResult
	2,  // 14: fluke.v1.StepCheckResult.check_outcome:type_name -> fluke.v1.CheckOutcome
	20, // 15: fluke.v1.ExecuteTask.task:type_name -> fluke.v1.TaskSpec
	0,  // 16: fluke.v1.StepLogLine.stream:type_name -> fluke.v1.LogStream
	1,  // 17: fluke.v1.StepResult.outcome:type_name -> fluke.v1.StepOutcome
	3,  // 18: fluke.v1.TaskComplete.outcome:type_name -> fluke.v1.TaskOutcome
	21, // 19: fluke.v1.TaskSpec.steps:type_name -> fluke.v1.StepSpec
	42, // 20: fluke.v1.StepSpec.env:type_name -> fluke.v1.StepSpec.EnvEntry
	4,  // 21: fluke.v1.StepSpec.on_failure:type_name -> fluke.v1.OnFailure
	26, // 22: fluke.v1.ListAgentsResponse.agents:type_name -> fluke.v1.AgentSummary
	26, // 23: fluke.v1.GetAgentResponse.agent:type_name -> fluke.v1.AgentSummary
	32, // 24: fluke.v1.GetAgentResponse.events:type_name -> fluke.v1.EventSummary
	43, // 25: fluke.v1.AgentSummary.labels:type_name -> fluke.v1.AgentSummary.LabelsEntry
	5,  // 26: fluke.v1.AgentSummary.status:type_name -> fluke.v1.AgentStatus
	29, // 27: fluke.v1.ListDriftResponse.entries:type_name -> fluke.v1.DriftEntry
	32, // 28: fluke.v1.ListEventsResponse.events:type_name -> fluke.v1.EventSummary
	3,  // 29: fluke.v1.EventSummary.outcome:type_name -> fluke.v1.TaskOutcome
	16, // 30: fluke.v1.ExecutionEvent.log_line:type_name -> fluke.v1.StepLogLine
	17, // 31: fluke.v1.ExecutionEvent.step_result:type_name -> fluke.v1.StepResult
	18, // 32: fluke.v1.ExecutionEvent.task_complete:type_name -> fluke.v1.TaskComplete
	37, // 33: fluke.v1.ReconciliationEvent.started:type_name -> fluke.v1.ReconcileStarted
	38, // 34: fluke.v1.ReconciliationEvent.agent_started:type_name -> fluke.v1.AgentReconcileStarted
	34, // 35: fluke.v1.ReconciliationEvent.execution:type_name -> fluke.v1.ExecutionEvent
	39, // 36: fluke.v1.ReconciliationEvent.agent_result:type_name -> fluke.v1.AgentReconcileResult
	40, // 37: fluke.v1.ReconciliationEvent.complete:type_name -> fluke.v1.ReconcileComplete
	3,  // 38: fluke.v1.AgentReconcileResult.outcome:type_name -> fluke.v1.TaskOutcome
	6,  // 39: fluke.v1.AgentService.Connect:input_type -> fluke.v1.AgentMessage
	22, // 40: fluke.v1.ManagementService.ListAgents:input_type -> fluke.v1.ListAgentsRequest
	24, // 41: fluke.v1.ManagementService.GetAgent:input_type -> fluke.v1.GetAgentRequest
	27, // 42: fluke.v1.ManagementService.ListDrift:input_type -> fluke.v1.ListDriftRequest
	30, // 43: fluke.v1.ManagementService.ListEvents:input_type -> fluke.v1.ListEventsRequest
	33, // 44: fluke.v1.ManagementService.StreamExecution:input_type -> fluke.v1.StreamExecutionRequest
	35, // 45: fluke.v1.ManagementService.TriggerReconcile:input_type -> fluke.v1.TriggerReconcileRequest
	7,  // 46: fluke.v1.AgentService.Connect:output_type -> fluke.v1.ServerMessage
	23, // 47: fluke.v1.ManagementService.ListAgents:output_type -> fluke.v1.ListAgentsResponse
	25, // 48: fluke.v1.ManagementService.GetAgent:output_type -> fluke.v1.GetAgentResponse
	28, // 49: fluke.v1.ManagementService.ListDrift:output_type -> fluke.v1.ListDriftResponse
	31, // 50: fluke.v1.ManagementService.ListEvents:output_type -> fluke.v1.ListEventsResponse
	34, // 51: fluke.v1.ManagementService.StreamExecution:output_type -> fluke.v1.ExecutionEvent
	36, // 52: fluke.v1.ManagementService.TriggerReconcile:output_type -> fluke.v1.ReconciliationEvent
	46, // [46:53] is the sub-list for method output_type
	39, // [39:46] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_internal_proto_fluke_proto_init() }
func file_internal_proto_fluke_proto_init() {
	if File_internal_proto_fluke_proto != nil {
		return
	}
	file_internal_proto_fluke_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_StateReport)(nil),
		(*AgentMessage_LogLine)(nil),
		(*AgentMessage_StepResult)(nil),
		(*AgentMessage_TaskComplete)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_internal_proto_fluke_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_RequestStateReport)(nil),
		(*ServerMessage_ExecuteTask)(nil),
		(*ServerMessage_CancelTask)(nil),
	}
	file_internal_proto_fluke_proto_msgTypes[28].OneofWrappers = []any{
		(*ExecutionEvent_LogLine)(nil),
		(*ExecutionEvent_StepResult)(nil),
		(*ExecutionEvent_TaskComplete)(nil),
	}
	file_internal_proto_fluke_proto_msgTypes[29].OneofWrappers = []any{
		(*TriggerReconcileRequest_TaskName)(nil),
		(*TriggerReconcileRequest_AgentId)(nil),
		(*TriggerReconcileRequest_All)(nil),
	}
	file_internal_proto_fluke_proto_msgTypes[30].OneofWrappers = []any{
		(*ReconciliationEvent_Started)(nil),
		(*ReconciliationEvent_AgentStarted)(nil),
		(*ReconciliationEvent_Execution)(nil),
		(*ReconciliationEvent_AgentResult)(nil),
		(*ReconciliationEvent_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_fluke_proto_rawDesc), len(file_internal_proto_fluke_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_fluke_proto_goTypes,
		DependencyIndexes: file_internal_proto_fluke_proto_depIdxs,
		EnumInfos:         file_internal_proto_fluke_proto_enumTypes,
		MessageInfos:      file_internal_proto_fluke_proto_msgTypes,
	}.Build()
	File_internal_proto_fluke_proto = out.File
	file_internal_proto_fluke_proto_goTypes = nil
	file_internal_proto_fluke_proto_depIdxs = nil
}
